version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: millie-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: millie_assignment
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db_data:/vdar/lib/mysqlky